fallback = 'ï‹'

[matching]
'discord' = 'ï’'
'balena-etcher' = 'ï‹›'
'Chia Blockchain' = 'ï“˜'
'Steam' = 'ï¶'
'vlc' = 'ï€½'
'org.qbittorrent.qBittorrent' = 'ï¶'
'Thunderbird' = 'ïƒ '
'thunderbird' = 'ïƒ '
'Postman' = 'ï '
'Insomnia' = 'ïˆ¶'
'Bitwarden' = 'ï‚„'
'Slack' = 'ï†˜'
'Code' = 'ï„¡'
'code-oss' = 'ï„¡'
'xed' = 'ï„¡'
'Spotify' = 'ï†¼'
'/NVIM ?\w*/' = 'ï‰½'
'/npm/' = 'ï¹'
'/node/' = 'ï¹'
'/yarn/' = 'ï¹'
'Alacritty' = 'ï„ '
'telegramdesktop' = 'ï¾'
'Telegram' = 'ï¾'
'Wfica' = 'ïŠ'
'org.remmina.Remmina' = 'ïŠ'
'SchildiChat' = 'ï³'
'Element' = 'ï³'
'nheko' = 'ï³'
'/Firefox .*Private Browsing/' = 'ï°'
'/(?i)Google Drive.*Firefox/' = 'ïª'
'/(?i)Google Calendar.*Firefox/' = 'ï³'
'/(?i)MAX.*Iridium/' = 'ïŠ‰'
'/(?i)Dashboards -.*Iridium/' = 'ï‚€'
'/(?i) youtube.*Firefox/' = 'ï…§'
'// Twitter.*Firefox/' = 'ï‚™'
'/ eBay.*Firefox/' = 'ï“´'
'/(?i)reddit.*Firefox/' = 'ïŠ'
'/(?i)drive.*Firefox/' = 'ïª'
'/(?i)Github.*Firefox/' = 'ï‚›'
'/Google.*Firefox/' = 'ï† '
'org.kde.dolphin' = 'ï¼'
'/home/.*Dolphin/' = 'ï€•'
'thunar' = { type = 'generic', value = 'ï»' }
'firefox' = 'ï‰©'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'
'Google-chrome' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Chromium-browser' = 'ï‰¨'
'org.kde.kcharselect' = 'ï“•'
'Zim' = 'ï„'
'image-roll' = 'ï€¾'
'pavucontrol' = 'ï€¨'
'obs' = 'ï†’'
'galculator' = 'ğŸ–©'
'mpv' = 'ğŸ'
'blueberry.py' = 'ïŠ”' 
'wdisplays' = 'ğŸ–µ'
'Pinta' = 'ğŸ–Œ'
'GParted' = 'ğŸ–´'
'/GParted/' = 'ğŸ–´'
'org.inkscape.Inkscape' = 'ğŸ–‹'
'/Application Launcher/' = ''
'vesktop' = 'ïš¾'

